speed_numbers = ["20", "30", "50", "60", "70", "90", "80", "100", "120"]

label_count_template = {
    "Person": None,
    "Fahrrad": None,
    "Auto": None,
    "Geschwindigkeit": None,
    "Ende 70": None,
    "Ende 80": None,
    "Ende Ueberholverbot": None,
    "Ende Ueberholverbot LKW": None,
    "Kreisverkehr": None,
    "Ampel": None,
    "Fahrt rechts vorbei": None,
    "Stop": None,
    "Fahrt links vorbei": None,
    "Ueberholverbot": None,
    "Ueberholverbot LKW": None,
    "Einmalige Vorfahrt": None,
    "Vorfahrtstrasse": None,
    "Vorfahrt gewaehren": None,
    "Verbot alle Fahrzeuge": None,
    "Verbot LKW": None,
    "Verbot Einfahrt": None,
    "Gefahrenstelle": None,
    "Kurve links": None,
    "Kurve rechts": None,
    "Doppelkurve links": None,
    "Unebene Fahrbahn": None,
    "Rutschgefahr": None,
    "Einseitig rechts verengt": None,
    "Arbeitsstelle": None,
    "Lichtzeichenanlage": None,
    "Fußgaenger": None,
    "Kinder": None,
    "Radfahrer": None,
    "Eisglaette": None,
    "Wildwechsel": None,
    "Ende Geschwindigkeit": None,
    "Fahrt rechts": None,
    "Fahrt links": None,
    "Fahrt geradeaus": None,
    "Fahrt geradeaus rechts": None,
    "Fahrt geradeaus links": None
}
